// RIGI Tracker — data layer
// Sources: Boletín Oficial (resoluciones ME), Casa Rosada, Infobae, Ámbito, La Nación, Cronista. Update: May 2026.

window.RIGI = {
  sectors: {
    oilgas:         { label: 'Oil & Gas',       color: '#475569' },
    mining:         { label: 'Minería',         color: '#2563eb' },
    energy:         { label: 'Energía',         color: '#059669' },
    infrastructure: { label: 'Infraestructura', color: '#d97706' }
  },

  statuses: {
    operativo:    { label: 'Operativo',       color: '#16a34a' },
    construccion: { label: 'En construcción', color: '#2563eb' },
    desarrollo:   { label: 'En desarrollo',   color: '#ca8a04' },
    ampliacion:   { label: 'En ampliación',   color: '#4f46e5' },
    exploracion:  { label: 'En exploración',  color: '#9333ea' },
    aprobado:     { label: 'Aprobado',        color: '#6b7280' },
    anunciado:    { label: 'Anunciado',       color: '#8b5cf6' }
  },

  // Province centroids on a 320x540 SVG of Argentina.
  // Coords derived from approximate lat/lon → SVG mapping for the project locations.
  provinces: {
    'Jujuy':         { region: 'NOA',       x: 122, y: 32 },
    'Salta':         { region: 'NOA',       x: 118, y: 60 },
    'Catamarca':     { region: 'NOA',       x: 112, y: 90 },
    'San Juan':      { region: 'Cuyo',      x: 92,  y: 140 },
    'Santa Fe':      { region: 'Litoral',   x: 198, y: 168 },
    'Mendoza':       { region: 'Cuyo',      x: 92,  y: 195 },
    'Buenos Aires':  { region: 'Pampeana',  x: 208, y: 248 },
    'Neuquén':       { region: 'Patagonia', x: 100, y: 278 },
    'Río Negro':     { region: 'Patagonia', x: 145, y: 318 }
  },

  projects: [
    {
      id: 1, sector: 'energy', status: 'operativo',
      name: 'Parque solar YPF Luz',
      company: 'YPF Luz',
      province: 'Mendoza',
      amount: 211,
      location: 'Las Heras, Mendoza',
      approvalDate: '2025-01-08',
      operationalDate: '2024 (100 MW) → 2026 (305 MW)',
      directJobs: 500,
      annualExportsUSDm: null,
      companyCountry: 'AR',
      ticker: 'YPF', tickerExchange: 'NYSE', tickerName: 'YPF S.A.',
      description: 'Primer proyecto del RIGI aprobado. Parque solar fotovoltaico de 305 MW de capacidad instalada, ya genera 100 MW y fue el primero del régimen en recibir habilitación de CAMMESA.',
      timeline: '2024: inaugurado · 100 MW operativos · 305 MW a capacidad total',
      impact: '305 MW renovables. Reducción de emisiones. Abastecimiento de la red de Mendoza.',
      opportunities: [
        'Mantenimiento de paneles y equipos eléctricos',
        'Monitoreo y optimización de generación con IA',
        'Expansión a nuevas fases del parque',
        'Servicios de seguridad operativa'
      ],
      companies: 'YPF Luz (subsidiaria de YPF)'
    },
    {
      id: 2, sector: 'oilgas', status: 'construccion',
      name: 'Vaca Muerta Oleoducto Sur (VMOS)',
      company: 'YPF + PAE + Vista + Pampa + Pluspetrol + Chevron + Shell',
      province: 'Neuquén',
      amount: 2486,
      location: 'Allen (Neuquén) → Punta Colorada (Río Negro)',
      approvalDate: '2025-03-21',
      operationalDate: 'Fin 2026',
      directJobs: null,
      annualExportsUSDm: null,
      companyCountry: null,
      ticker: null, tickerExchange: null, tickerName: null,
      description: 'Oleoducto de 437 km que conectará la producción de Vaca Muerta con Punta Colorada para exportación. Operativo hacia fines de 2026.',
      timeline: '2025–2026: construcción · Fin 2026: puesta en operación',
      impact: 'Duplicación de la capacidad exportadora petrolera. Reducción de costos logísticos. Miles de empleos.',
      opportunities: [
        'Cañerías y válvulas de alta presión',
        'Ingeniería de detalle y supervisión de obra',
        'Sistemas de monitoreo y detección de fugas',
        'Bombas y equipos de impulsión',
        'Soldadura especializada',
        'Campamentos y logística'
      ],
      companies: 'Joint venture: YPF, Pan American Energy, Vista Energy, Pampa Energía, Pluspetrol, Chevron, Shell'
    },
    {
      id: 3, sector: 'oilgas', status: 'desarrollo',
      name: 'GNL PAE-Golar / Southern Energy',
      company: 'Southern Energy (PAE + Golar)',
      province: 'Río Negro',
      amount: 6878,
      location: 'Golfo San Matías, Río Negro',
      approvalDate: '2025-05-05',
      operationalDate: '2027–2028',
      directJobs: null,
      annualExportsUSDm: null,
      companyCountry: 'BM',
      ticker: 'GLNG', tickerExchange: 'NASDAQ', tickerName: 'Golar LNG Ltd',
      description: 'Megaproyecto de licuefacción de gas natural. Permitirá exportar GNL desde Vaca Muerta a mercados internacionales. La inversión más grande del RIGI.',
      timeline: '2027: inicio de licuefacción',
      impact: 'Argentina como exportador de GNL. Divisas por miles de millones. Demanda sostenida de gas de Vaca Muerta.',
      opportunities: [
        'Ingeniería criogénica',
        'Buques metaneros y logística portuaria',
        'Compresión y tratamiento de gas',
        'Mantenimiento criogénico',
        'Inspección y certificación',
        'Proveedores locales para GNL'
      ],
      companies: 'Southern Energy (joint venture PAE + Golar LNG)'
    },
    {
      id: 4, sector: 'mining', status: 'desarrollo',
      name: 'Río Tinto · Litio Salar de Rincón',
      company: 'Río Tinto',
      province: 'Salta',
      amount: 2700,
      location: 'Salar de Rincón, Salta',
      approvalDate: '2025-06-03',
      operationalDate: '2028',
      directJobs: 2500,
      annualExportsUSDm: null,
      companyCountry: 'GB',
      ticker: 'RIO', tickerExchange: 'NYSE', tickerName: 'Rio Tinto plc',
      description: 'Extracción y procesamiento de litio en el Salar de Rincón. La minera anglo-australiana apuesta por Argentina como hub global de litio.',
      timeline: '2025–2028: construcción y puesta en marcha',
      impact: 'Salta en el mapa del litio. Carbonato de litio de alta calidad para baterías. Empleo en la Puna salteña.',
      opportunities: [
        'Perforación y exploración',
        'Plantas de evaporación y proceso químico',
        'Equipos para manejo de salmueras',
        'Laboratorios de control',
        'Campamentos en la Puna',
        'Transporte de insumos y producto'
      ],
      companies: 'Río Tinto (Reino Unido / Australia)'
    },
    {
      id: 5, sector: 'infrastructure', status: 'desarrollo',
      name: 'Sidersa · Planta siderúrgica',
      company: 'Sidersa',
      province: 'Buenos Aires',
      amount: 286,
      location: 'San Nicolás, Buenos Aires',
      approvalDate: '2025-07-22',
      operationalDate: '2028 H1',
      directJobs: 300,
      annualExportsUSDm: 360,
      companyCountry: 'AR',
      ticker: null, tickerExchange: null, tickerName: null,
      description: 'Nueva planta siderúrgica para 360.000 toneladas anuales de insumos para industria nacional y exportación.',
      timeline: '2025–2027: construcción y puesta en marcha',
      impact: '360 mil tn/año de acero. Sustitución de importaciones. Integración con la cadena minera y energética.',
      opportunities: [
        'Ingeniería siderúrgica',
        'Equipos de laminación y hornos',
        'Manejo de materiales y logística pesada',
        'Mantenimiento industrial',
        'Comercialización de acero',
        'Transporte ferroviario y portuario'
      ],
      companies: 'Sidersa'
    },
    {
      id: 6, sector: 'mining', status: 'desarrollo',
      name: 'Salar del Hombre Muerto',
      company: 'Galan Lithium',
      province: 'Catamarca',
      amount: 217,
      location: 'Salar del Hombre Muerto, Catamarca',
      approvalDate: '2025-08-28',
      operationalDate: '2026 H1',
      directJobs: null,
      annualExportsUSDm: 180,
      companyCountry: 'AU',
      ticker: 'GLN.AX', tickerExchange: 'ASX', tickerName: 'Galan Lithium Limited',
      description: 'Proyecto de cloruro de litio de la firma australiana Galan Lithium. Exportará US$180 M anuales desde 2029.',
      timeline: '2027–2029: construcción · 2029: US$180 M/año en exportaciones',
      impact: 'US$180 M/año en exportaciones. Empleo en Catamarca. Cadena de valor del litio.',
      opportunities: [
        'Perforación y bombeo de salmueras',
        'Equipos de evaporación solar',
        'Análisis químico y control',
        'Logística en la Puna catamarqueña',
        'Construcción de campamentos'
      ],
      companies: 'Galan Lithium (Australia)'
    },
    {
      id: 7, sector: 'energy', status: 'desarrollo',
      name: 'Parque eólico Olavarría',
      company: 'Acindar / PCR',
      province: 'Buenos Aires',
      amount: 250,
      location: 'Olavarría, Buenos Aires',
      approvalDate: '2025-08-27',
      operationalDate: '2026 Q4',
      directJobs: null,
      annualExportsUSDm: null,
      companyCountry: 'LU',
      ticker: 'MT', tickerExchange: 'NYSE', tickerName: 'ArcelorMittal SA',
      description: 'Parque eólico de 180 MW impulsado por Acindar (ArcelorMittal) y PCR. Energía renovable para la industria del acero y el SADI.',
      timeline: '2025–2027: construcción y conexión a red',
      impact: '180 MW renovables. Abastecimiento directo a la industria siderúrgica. Menor huella de carbono.',
      opportunities: [
        'Montaje de aerogeneradores',
        'Obra civil de fundaciones y caminos',
        'Mantenimiento de turbinas',
        'Almacenamiento de energía',
        'Subestaciones y conexión eléctrica'
      ],
      companies: 'Acindar (ArcelorMittal), PCR'
    },
    {
      id: 8, sector: 'mining', status: 'exploracion',
      name: 'Los Azules',
      company: 'McEwen Copper',
      province: 'San Juan',
      amount: 2672,
      location: 'San Juan',
      approvalDate: '2025-10-14',
      operationalDate: '2029–2030',
      directJobs: null,
      annualExportsUSDm: null,
      companyCountry: 'CA',
      ticker: 'MUX', tickerExchange: 'NYSE', tickerName: 'McEwen Mining Inc.',
      description: 'Uno de los proyectos de cobre más importantes del país. Exploración avanzada y estudio de factibilidad en curso.',
      timeline: '2025–2028: exploración, factibilidad y construcción',
      impact: 'Cobre de clase mundial. San Juan como provincia minera. Empleo directo e indirecto.',
      opportunities: [
        'Perforación diamantina y exploración',
        'Estudios de impacto ambiental',
        'Ingeniería de mina y planta concentradora',
        'Caminos e infraestructura vial',
        'Chancado y molienda',
        'Logística de equipos y suministros'
      ],
      companies: 'McEwen Copper (subsidiaria de McEwen Mining, Canadá)'
    },
    {
      id: 9, sector: 'infrastructure', status: 'desarrollo',
      name: 'Puerto multipropósito Timbúes',
      company: 'Por confirmar',
      province: 'Santa Fe',
      amount: 277,
      location: 'Timbúes, Santa Fe',
      approvalDate: '2025-11-20',
      operationalDate: '2027–2028',
      directJobs: 200,
      annualExportsUSDm: null,
      companyCountry: 'AR',
      ticker: null, tickerExchange: null, tickerName: null,
      description: 'Complejo logístico portuario para fertilizantes, hierro, productos siderúrgicos, granos y combustibles. Refuerza el polo agroindustrial santafesino.',
      timeline: '2025–2027: construcción',
      impact: 'Mayor capacidad de exportación/importación. Menor costo logístico para agro e industria. Integración con el Gran Rosario.',
      opportunities: [
        'Dragado y obras portuarias',
        'Equipos de carga y descarga',
        'Silos y almacenes',
        'Gestión logística y operación portuaria',
        'Conexión ferroviaria y vial',
        'Servicios a buques'
      ],
      companies: 'Por confirmar'
    },
    {
      id: 10, sector: 'mining', status: 'desarrollo',
      name: 'Gualcamayo',
      company: 'Minas Argentinas (Aisa Group)',
      province: 'San Juan',
      amount: 665,
      location: 'San Juan',
      approvalDate: '2026-01-15',
      operationalDate: '2027–2028',
      directJobs: 1700,
      annualExportsUSDm: null,
      companyCountry: 'ES',
      ticker: null, tickerExchange: null, tickerName: null,
      description: 'Ampliación de explotación de oro y plata con esquema de mineralización diferente. Alto impacto en empleo directo.',
      timeline: '2025–2028: nuevo esquema de explotación',
      impact: 'Extensión de vida útil. Empleo directo en San Juan. Producción sostenida de oro y plata.',
      opportunities: [
        'Equipos de minería subterránea',
        'Ventilación y seguridad minera',
        'Plantas de procesamiento',
        'Transporte de mineral',
        'Perforación y voladura'
      ],
      companies: 'Minas Argentinas (Aisa Group, España)'
    },
    {
      id: 11, sector: 'mining', status: 'ampliacion',
      name: 'Veladero',
      company: 'Barrick Mining',
      province: 'San Juan',
      amount: 380,
      location: 'San Juan',
      approvalDate: '2026-02-27',
      operationalDate: '2026 Q4',
      directJobs: 1100,
      annualExportsUSDm: 425,
      companyCountry: 'CA',
      ticker: 'B', tickerExchange: 'NYSE', tickerName: 'Barrick Mining Corporation',
      description: 'Ampliación de la mina de oro y plata Veladero. Una de las más importantes del país recibe inversión para extender su producción.',
      timeline: '2025–2027: ampliación y nuevos tajos',
      impact: 'Extensión de vida útil. Mantenimiento de empleo. Producción continua de oro y plata.',
      opportunities: [
        'Movimiento de suelo y cielo abierto',
        'Carguío y transporte',
        'Mantenimiento de flota minera',
        'Tronadura',
        'Gestión de residuos mineros'
      ],
      companies: 'Barrick Mining (Canadá)'
    },
    {
      id: 12, sector: 'mining', status: 'desarrollo',
      name: 'Diablillos',
      company: 'AbraSilver',
      province: 'Salta',
      amount: 760,
      location: 'Salta y Catamarca',
      approvalDate: '2026-05-11',
      operationalDate: '2029 Q3',
      directJobs: null,
      annualExportsUSDm: 417,
      companyCountry: 'CA',
      ticker: 'ABRA.TO', tickerExchange: 'TSX', tickerName: 'AbraSilver Resource Corp.',
      description: 'Nueva mina de oro y plata de AbraSilver en la frontera entre Salta y Catamarca. Generará 1.200 empleos directos y US$417 M anuales de exportación.',
      timeline: '2025–2028: construcción y puesta en marcha',
      impact: '1.200 empleos directos. US$417 M/año en exportaciones. Desarrollo del NOA.',
      opportunities: [
        'Construcción de planta de procesos',
        'Molienda y flotación',
        'Campamentos e infraestructura',
        'Logística de insumos y producción',
        'Estudios geotécnicos y ambientales'
      ],
      companies: 'AbraSilver (Canadá)'
    },
    {
      id: 13, sector: 'mining', status: 'ampliacion',
      name: 'Fénix',
      company: 'Río Tinto',
      province: 'Catamarca',
      amount: 530,
      location: 'Catamarca',
      approvalDate: '2026-03-26',
      operationalDate: '2026 Q3',
      directJobs: null,
      annualExportsUSDm: null,
      companyCountry: 'GB',
      ticker: 'RIO', tickerExchange: 'NYSE', tickerName: 'Rio Tinto plc',
      description: 'Ampliación de la producción de litio en Catamarca por parte de Río Tinto. Refuerza la apuesta global por Argentina como hub de litio para baterías.',
      timeline: '2026–2029: ampliación de producción',
      impact: 'Más producción de litio en Catamarca. Más exportaciones y empleo local.',
      opportunities: [
        'Piletas de evaporación',
        'Equipos de proceso químico',
        'Mantenimiento industrial',
        'Servicios de laboratorio',
        'Infraestructura en la Puna'
      ],
      companies: 'Río Tinto (Reino Unido / Australia)'
    },
    {
      id: 14, sector: 'oilgas', status: 'desarrollo',
      name: 'Ampliación Gasoducto Perito Moreno',
      company: 'TGS',
      province: 'Neuquén',
      amount: 550,
      location: 'Neuquén → Buenos Aires',
      approvalDate: '2026-05-13',
      operationalDate: '2027 Q2',
      directJobs: null,
      annualExportsUSDm: null,
      companyCountry: 'AR',
      ticker: 'TGS', tickerExchange: 'NYSE', tickerName: 'Transportadora de Gas del Sur SA',
      description: 'Refuerzo de transporte de gas natural en 14 MM m³/día desde Vaca Muerta hacia Buenos Aires. Obra crítica para abastecer demanda interna y posibilitar más exportaciones.',
      timeline: '2025–2027: construcción',
      impact: '+14 MM m³/d de capacidad. Abastecimiento industrial y residencial. Más exportaciones a Chile y Brasil.',
      opportunities: [
        'Cañerías de gran diámetro',
        'Estaciones de compresión',
        'Ingeniería de gasoductos',
        'Soldadura y tendido',
        'Válvulas y control',
        'Estudios de impacto ambiental'
      ],
      companies: 'Transportadora Gas del Sur (TGS)'
    },
    {
      id: 15, sector: 'mining', status: 'ampliacion',
      name: 'Cauchari-Olaroz',
      company: 'Ganfeng + Lithium Americas + JEMSE',
      province: 'Jujuy',
      amount: 1241,
      location: 'Salar Cauchari-Olaroz, Jujuy',
      approvalDate: '2026-05-14',
      operationalDate: '2028–2029',
      directJobs: null,
      annualExportsUSDm: null,
      companyCountry: 'CA',
      ticker: 'LAC', tickerExchange: 'NYSE', tickerName: 'Lithium Americas Corp.',
      description: 'Ampliación del proyecto de litio para alcanzar 40.000 tn/año. Joint venture entre la china Ganfeng, Lithium Americas y la estatal jujeña JEMSE.',
      timeline: '2025–2027: ampliación a 40.000 tn/año',
      impact: '40.000 tn/año de carbonato de litio. Uno de los proyectos de litio más grandes del país. Empleo en Jujuy.',
      opportunities: [
        'Planta de carbonato de litio',
        'Evaporación y cristalización',
        'Laboratorios de ensayo',
        'Campamentos mineros',
        'Transporte a puerto',
        'Provisión de energía'
      ],
      companies: 'Ganfeng Lithium (China), Lithium Americas (Canadá), JEMSE (Jujuy)'
    },
    {
      id: 16, sector: 'mining', status: 'aprobado',
      name: 'Proyecto San Jorge (PSJ)',
      company: 'Zonda Metals + Alberdi Energy',
      province: 'Mendoza',
      amount: 891,
      location: 'Uspallata, Mendoza',
      approvalDate: '2026-05-14',
      operationalDate: '2029–2030',
      directJobs: null,
      annualExportsUSDm: null,
      companyCountry: 'CH',
      ticker: null, tickerExchange: null, tickerName: null,
      description: 'Megaproyecto minero de cobre en Uspallata. Aprobado por el Gobierno el 14 de mayo de 2026. Pertenece a la suiza Zonda Metals y la argentina Alberdi Energy.',
      timeline: '2026–2030: construcción y producción',
      impact: 'Cobre de alta ley. Primera gran mina de cobre en Mendoza. Empleo en Uspallata. Exportaciones estratégicas.',
      opportunities: [
        'Ingeniería de mina y planta concentradora',
        'Chancado primario',
        'Caminos de acceso y obra civil',
        'Instalaciones eléctricas y subestaciones',
        'Logística de equipos pesados',
        'Gestión de recursos hídricos',
        'Hotelería y alimentación de personal'
      ],
      companies: 'Zonda Metals GmbH (Suiza), Alberdi Energy (Argentina)'
    }
  ]

  pendingProjects: [
    {
      id: 'A', sector: 'oilgas', status: 'anunciado',
      name: 'LLL Oil',
      company: 'YPF',
      province: 'Neuquén',
      amount: 25000,
      location: 'Vaca Muerta, Neuquén',
      announcementDate: '2026-05-15',
      decisionDate: '2026–2027',
      directJobs: 6000,
      annualExportsUSDm: 6000,
      companyCountry: 'AR',
      ticker: 'YPF', tickerExchange: 'NYSE', tickerName: 'YPF S.A.',
      description: 'Megaproyecto de exportación de petróleo presentado al RIGI por YPF en mayo de 2026. 1.152 pozos en 15 años con una inversión de US$25.000 M. Producción de 240.000 barriles diarios a partir de 2032. El 100% del crudo se exportará por VMOS.',
      timeline: '2026: presentación al RIGI · 2032: plateau de 240.000 bbl/d · 15 años de inversión',
      impact: 'US$100.000 M+ en exportaciones durante la vida del proyecto. 6.000 empleos directos. Consolidación de Vaca Muerta como hub exportador.',
      opportunities: [
        'Perforación y completación de pozos',
        'Fractura hidráulica y sets de pressure pumping',
        'Logística de arena, agua y equipos',
        'Ingeniería de superficie y ductos',
        'Campamentos y servicios para 6.000 trabajadores',
        'Mantenimiento de equipos de perforación',
        'Monitoreo digital y automatización',
        'Transporte de crudo y logística portuaria'
      ],
      companies: 'YPF S.A. (Argentina)'
    },
    {
      id: 'B', sector: 'oilgas', status: 'anunciado',
      name: 'Argentina GNL',
      company: 'YPF + ENI + XRG',
      province: 'Río Negro',
      amount: 30000,
      location: 'Golfo San Matías, Río Negro',
      announcementDate: '2026-01',
      decisionDate: '2S 2026 (FID)',
      directJobs: 40000,
      annualExportsUSDm: null,
      companyCountry: 'AR',
      ticker: 'YPF', tickerExchange: 'NYSE', tickerName: 'YPF S.A.',
      description: 'Megaproyecto de gas natural licuado con ENI (Italia) y XRG (EAU). Dos unidades flotantes de licuefacción con capacidad conjunta de 12 millones de tn/año. Inversión total de US$30.000 M: US$20.000 M en infraestructura + US$10.000 M en pozos.',
      timeline: '2025–2026: acuerdo y estructuración · 2S 2026: decisión final de inversión · 2030: inicio de exportaciones',
      impact: 'Hasta 50.000 empleos. Argentina como exportador de GNL. Integración con Vaca Muerta.',
      opportunities: [
        'Ingeniería criogénica y plantas de licuefacción',
        'Buques metaneros y logística portuaria',
        'Compresión y tratamiento de gas',
        'Cañerías de interconexión',
        'Servicios de inspección y certificación',
        'Construcción naval y mantenimiento',
        'Provisión de energía para las operaciones',
        'Hotelería y servicios para 40.000 trabajadores'
      ],
      companies: 'YPF (Argentina), ENI (Italia), XRG (Emiratos Árabes Unidos)'
    }
  ]
};